# Generated by Django 4.0.4 on 2022-04-27 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Checkbook', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='First_name',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='account',
            name='Initial_deposit',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='account',
            name='Last_name',
            field=models.CharField(max_length=60),
        ),
    ]
