# Generated by Django 4.0.4 on 2022-04-27 01:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Checkbook', '0002_alter_account_first_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='First_name',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='account',
            old_name='Initial_deposit',
            new_name='initial_deposit',
        ),
        migrations.RenameField(
            model_name='account',
            old_name='Last_name',
            new_name='last_name',
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='Account',
            new_name='account',
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='Amount',
            new_name='amount',
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='Date',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='Description',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='Type',
            new_name='type',
        ),
    ]
