# Generated by Django 4.0.4 on 2022-04-26 01:37

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='djangoClasses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=60)),
                ('Course', models.IntegerField(blank=True, default='', max_length=10)),
                ('Instructor_Name', models.CharField(default='', max_length=60)),
                ('Duration', models.FloatField(default=1650937023.3105714, max_length=10)),
            ],
            managers=[
                ('Class_Library', django.db.models.manager.Manager()),
            ],
        ),
    ]
